// SPDX-License-Identifier: Apache-2.0
// Copyright 2025-2026 Colin Farmer (GitCmurf)

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

describe('Generated Files Synchronization', () => {
  it('types.generated.ts should exist and have content', () => {
    const content = readFileSync(join(__dirname, '../src/types.generated.ts'), 'utf-8');
    expect(content).toContain('This file was automatically generated by json-schema-to-typescript');
    expect(content).toContain('export interface AIDHAConfiguration');
  });

  it('schema.generated.ts should exist and have metadata', () => {
    const content = readFileSync(join(__dirname, '../src/schema.generated.ts'), 'utf-8');
    expect(content).toContain('export const PATH_PATTERNS');
    expect(content).toContain('export const SECRET_LEAF_NAMES');
    expect(content).toContain('export const COERCION_MAP');
  });
});
