// @ts-nocheck
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm gen:types` to regenerate this file.
 */

/**
 * Schema for AIDHA config files (~/.config/aidha/config.yaml or .aidha/config.yaml). See AIDHA-PLAN-005.
 */
export interface AIDHAConfiguration {
  /**
   * Schema version. Must match or be lower than the binary's SUPPORTED_CONFIG_VERSION.
   */
  config_version: number;
  /**
   * Override computed base directory for resolving relative paths.
   */
  base_dir?: string;
  /**
   * Optional dotenv loading configuration (loaded before interpolation).
   */
  env?: {
    /**
     * Dotenv files to load in-order. Paths relative to base_dir_prelim.
     */
    dotenv_files?: string[];
    /**
     * If true, dotenv values override existing process.env values.
     */
    override_existing?: boolean;
    /**
     * If true, missing dotenv files cause an error instead of a warning.
     */
    dotenv_required?: boolean;
  };
  /**
   * Name of the default profile to use when none is specified.
   */
  default_profile: string;
  /**
   * Named configuration profiles. The 'default' profile should be complete.
   */
  profiles: {
    [k: string]: Profile;
  };
  /**
   * Ingestion-source defaults. Keys are source IDs (e.g., 'youtube').
   */
  sources?: {
    [k: string]: SourceDefaults;
  };
  /**
   * Explicit extension point for custom/private keys. Not validated beyond being a JSON object.
   */
  extensions?: {
    [k: string]: unknown;
  };
}
/**
 * A configuration profile. Named profiles only need keys they want to override. Source-private fields belong in source_overrides.
 */
export interface Profile {
  /**
   * Path to the SQLite database.
   */
  db?: string;
  llm?: LlmConfig;
  editor?: EditorConfig;
  extraction?: ExtractionConfig;
  export?: ExportConfig;
  /**
   * Source-owned profile overrides keyed by source ID.
   */
  source_overrides?: {
    [k: string]: SourceOverride;
  };
  /**
   * Per-profile extension point.
   */
  extensions?: {
    [k: string]: unknown;
  };
}
export interface LlmConfig {
  /**
   * LLM model identifier.
   */
  model?: string;
  /**
   * LLM API key. Use ${VAR} interpolation for secrets.
   */
  api_key?: string;
  /**
   * LLM API base URL.
   */
  base_url?: string;
  /**
   * LLM request timeout in milliseconds.
   */
  timeout_ms?: number;
  /**
   * Directory for LLM response caching.
   */
  cache_dir?: string;
  /**
   * GPT-5 reasoning depth control.
   */
  reasoning_effort?: 'none' | 'minimal' | 'low' | 'medium' | 'high' | 'xhigh';
  /**
   * GPT-5 response verbosity control.
   */
  verbosity?: 'low' | 'medium' | 'high';
  /**
   * Number of items to send in a single batch embedding request.
   */
  embedding_batch_size?: number;
  /**
   * Task type for Gemini embeddings.
   */
  embedding_task_type?:
    | 'SEMANTIC_SIMILARITY'
    | 'RETRIEVAL_QUERY'
    | 'RETRIEVAL_DOCUMENT'
    | 'CLASSIFICATION'
    | 'CLUSTERING';
  /**
   * Output dimensionality for Gemini embeddings.
   */
  embedding_output_dimensionality?: number;
}
export interface EditorConfig {
  /**
   * Editor version (v1 or v2).
   */
  version?: string;
  /**
   * Sliding window size in minutes.
   */
  window_minutes?: number;
  /**
   * Maximum claims per window.
   */
  max_per_window?: number;
  /**
   * Minimum number of windows required.
   */
  min_windows?: number;
  /**
   * Minimum words per claim.
   */
  min_words?: number;
  /**
   * Minimum characters per claim.
   */
  min_chars?: number;
  /**
   * Whether to use LLM for editor refinement.
   */
  editor_llm?: boolean;
}
export interface ExtractionConfig {
  /**
   * Maximum claims to extract (0 = unlimited).
   */
  max_claims?: number;
  /**
   * Transcript chunk size in minutes.
   */
  chunk_minutes?: number;
  /**
   * Maximum chunks to process (0 = unlimited).
   */
  max_chunks?: number;
  /**
   * Prompt version for claim extraction.
   */
  prompt_version?: string;
}
export interface ExportConfig {
  /**
   * Prefix for exported claim IDs.
   */
  source_prefix?: string;
  /**
   * Output directory for exports.
   */
  out_dir?: string;
}
/**
 * Source-specific profile overrides. Core profile sections are validated; source-private sections remain opaque.
 */
export interface SourceOverride {
  /**
   * Path to the SQLite database.
   */
  db?: string;
  llm?: LlmConfig;
  editor?: EditorConfig;
  extraction?: ExtractionConfig;
  export?: ExportConfig;
  /**
   * Per-source extension point.
   */
  extensions?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Ingestion-source defaults. Core profile sections are validated; source-private sections are allowed for source registrations.
 */
export interface SourceDefaults {
  /**
   * Path to the SQLite database.
   */
  db?: string;
  llm?: LlmConfig;
  editor?: EditorConfig;
  extraction?: ExtractionConfig;
  export?: ExportConfig;
  /**
   * Per-source extension point.
   */
  extensions?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
