// SPDX-License-Identifier: Apache-2.0
// Copyright 2025-2026 Colin Farmer (GitCmurf)

import { compileFromFile } from 'json-schema-to-typescript';
import { writeFileSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SCHEMA_PATH = join(__dirname, '..', 'schema', 'config.schema.json');
const TYPES_OUT_PATH = join(__dirname, '..', 'src', 'types.generated.ts');
const METADATA_OUT_PATH = join(__dirname, '..', 'src', 'schema.generated.ts');

async function generateTypes() {
  console.log('Generating types from schema...');
  const ts = await compileFromFile(SCHEMA_PATH, {
    bannerComment: '// @ts-nocheck\n/* eslint-disable */\n/**\n * This file was automatically generated by json-schema-to-typescript.\n * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,\n * and run `pnpm gen:types` to regenerate this file.\n */',
    style: {
      singleQuote: true,
    },
  });
  writeFileSync(TYPES_OUT_PATH, ts);
  console.log(`Types written to ${TYPES_OUT_PATH}`);
}

function toCamelCase(str) {
  return str.replace(/_([a-z])/g, (g) => g[1].toUpperCase());
}

function generateMetadata() {
  console.log('Generating metadata from schema...');
  const schema = JSON.parse(readFileSync(SCHEMA_PATH, 'utf-8'));

  const pathPatterns = [];
  const runtimePathPatterns = [];
  const secretLeafNames = new Set();
  const coercionMap = {};

  const defs = schema.$defs || {};

  function deref(obj) {
    if (!obj || typeof obj !== 'object') return obj;
    if (obj.$ref) {
      const refName = obj.$ref.replace('#/$defs/', '');
      return defs[refName];
    }
    return obj;
  }

  function walk(obj, path = []) {
    const node = deref(obj);
    if (!node || typeof node !== 'object') return;

    const leaf = path[path.length - 1];

    // Secret fields
    if (node['x-aidha-secret'] === true && path.length > 0) {
      secretLeafNames.add(leaf);
    }

    // Path fields
    if (node['x-aidha-path'] === true && path.length > 0) {
      pathPatterns.push(path);

      // For runtime resolution (ResolvedConfig), we need camelCase paths
      // Note: ResolvedConfig is flatter (no 'profiles.*' prefix for core fields)
      // but 'activeSourceConfig' might still be snake_case.
      if (path[0] === 'profiles' && path[1] === '*') {
         runtimePathPatterns.push(path.slice(2).map(toCamelCase));
      } else {
         runtimePathPatterns.push(path.map(toCamelCase));
      }
    }

    // Coercion map (leaf scalar types)
    if (node.type && ['integer', 'number', 'boolean'].includes(node.type) && path.length > 0) {
      coercionMap[path.join('.')] = node.type;
    }

    if (node.properties) {
      for (const [key, val] of Object.entries(node.properties)) {
        walk(val, [...path, key]);
      }
    }

    if (node.additionalProperties && typeof node.additionalProperties === 'object') {
      walk(node.additionalProperties, [...path, '*']);
    }

    for (const keyword of ['allOf', 'anyOf', 'oneOf']) {
      if (Array.isArray(node[keyword])) {
        for (const sub of node[keyword]) walk(sub, path);
      }
    }

    if (node.items) walk(node.items, [...path, '*']);
    if (node.then) walk(node.then, path);
    if (node.else) walk(node.else, path);

    // Also check definitions for secrets (fallback discovery)
    if (node === schema) {
       for (const def of Object.values(defs)) {
          walk(def, []); // walk defs without path to find secrets
       }
    }
  }

  walk(schema);

  const metadata = `// @ts-nocheck
/* eslint-disable */
/**
 * This file was automatically generated.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run \`pnpm gen:types\` to regenerate this file.
 */

export const PATH_PATTERNS: string[][] = ${JSON.stringify(pathPatterns, null, 2)};

export const RUNTIME_PATH_PATTERNS: string[][] = ${JSON.stringify(runtimePathPatterns, null, 2)};

export const SECRET_LEAF_NAMES: string[] = ${JSON.stringify(Array.from(secretLeafNames).sort(), null, 2)};

export const COERCION_MAP: Record<string, 'integer' | 'number' | 'boolean'> = ${JSON.stringify(coercionMap, null, 2)};
`;

  writeFileSync(METADATA_OUT_PATH, metadata);
  console.log(`Metadata written to ${METADATA_OUT_PATH}`);
}


async function main() {
  try {
    await generateTypes();
    generateMetadata();
    console.log('Done.');
  } catch (err) {
    console.error('Failed to generate types:', err);
    process.exit(1);
  }
}

main();
